import Foundation

/// Current seed inventory for `TypographyEscapeeLintTests`.
enum TypographyEscapeeAllowlist {
    static let rows = #"""
# Phase 6 typography escapee seed inventory.
# path\tclassification\tmatch ordinal on source line\texact trimmed source line
# Classifications: sf-symbol (intentional icon sizing), overflow-exemption (+N fitted glyph), typography-debt.
AnnualBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: AnnualTypography.microLabelSize, weight: .regular, design: .monospaced))
AnnualClosedPill.swift	overflow-exemption	1	.font(.system(size: max(5, size * 0.55), weight: .bold, design: .monospaced))
AnnualEmptyState.swift	typography-debt	1	.font(.system(size: AnnualTypography.microLabelSize, weight: .regular, design: .monospaced))
AnnualHeaderControls.swift	sf-symbol	1	.font(.system(size: 12, weight: .regular))
AnnualInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 11, weight: .regular))
AnnualInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 9, weight: .regular))
AnnualSessionListScaffold.swift	typography-debt	1	.font(.system(size: AnnualTypography.countSize, weight: .regular, design: .monospaced))
AnnualSessionListScaffold.swift	typography-debt	1	.font(.system(size: AnnualTypography.microLabelSize, weight: .regular, design: .monospaced))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .bold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .bold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 22))
AnnualSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 10, weight: .medium, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .regular, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .regular, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .regular, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .medium, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .regular, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: kind == .strong ? .semibold : .medium, design: .monospaced))
AnnualSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .monospaced)
AnnualSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .monospaced)
AnnualUsageSummary.swift	typography-debt	1	.font(.system(size: 11, weight: .regular, design: .default))
FlightDeckBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .regular, design: .monospaced))
FlightDeckClosedPill.swift	overflow-exemption	1	.font(.system(size: max(5, size * 0.55), weight: .bold, design: .monospaced))
FlightDeckClosedPill.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .bold, design: .monospaced))
FlightDeckClosedPill.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .monospaced))
FlightDeckClosedPill.swift	typography-debt	1	.font(.system(size: Self.size, weight: .medium, design: .default))
FlightDeckClosedPill.swift	typography-debt	1	.font(.system(size: Self.size, weight: .medium, design: .monospaced))
FlightDeckEmptyState.swift	typography-debt	1	.font(.system(size: 12.5, weight: .regular, design: FlightDeckTypography.Family.sans.design))
FlightDeckEmptyState.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .regular, design: .monospaced))
FlightDeckHeaderControls.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
FlightDeckInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
FlightDeckInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
FlightDeckSessionListScaffold.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .semibold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 12, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 22))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .bold))
FlightDeckSessionRow.swift	sf-symbol	1	.font(.system(size: 9.5, weight: .semibold))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced).monospacedDigit())
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .bold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .bold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .medium))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .semibold, design: .monospaced).monospacedDigit())
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .heavy, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 13, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 13, weight: .medium, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: 13, weight: .medium, design: .monospaced).monospacedDigit())
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .bold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .default))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .default))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .default))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .default))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .default))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .monospaced))
FlightDeckSessionRow.swift	typography-debt	1	.font(.system(size: FlightDeckTypography.microLabelSize, weight: .semibold, design: .monospaced).monospacedDigit())
FlightDeckSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .default)
FlightDeckSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .default)
FlightDeckSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .monospaced)
FlightDeckSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .monospaced)
FlightDeckSessionRow.swift	typography-debt	1	baseFont: .system(size: 11.5, weight: .regular, design: .monospaced)
HaloBootstrapPlaceholder.swift	sf-symbol	1	.font(.system(size: 30, weight: .thin))
HaloBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: HaloTypography.emptySubtitleSize, weight: .regular))
HaloBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: HaloTypography.emptyTitleSize, weight: .semibold))
HaloClosedPill.swift	overflow-exemption	1	.font(.system(size: max(5, size * 0.55), weight: .bold, design: .monospaced))
HaloClosedPill.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
HaloClosedPill.swift	sf-symbol	1	.font(.system(size: weightAndSize.size, weight: weightAndSize.weight))
HaloClosedPill.swift	typography-debt	1	.font(.system(size: 12, weight: .bold, design: .default))
HaloClosedPill.swift	typography-debt	1	.font(.system(size: HaloTypography.pillLabelSize, weight: .regular, design: .default))
HaloClosedPill.swift	typography-debt	1	.font(.system(size: HaloTypography.pillLabelSize, weight: .semibold, design: .default))
HaloClosedPill.swift	typography-debt	1	.font(.system(size: HaloTypography.pillLabelSize, weight: .semibold, design: .default))
HaloClosedPill.swift	typography-debt	1	.font(.system(size: HaloTypography.pillValueSize, weight: .regular, design: .monospaced))
HaloClosedPill.swift	typography-debt	1	.font(.system(size: HaloTypography.usageKickerSize, weight: .regular, design: .default))
HaloClosedPill.swift	typography-debt	1	return .system(size: HaloTypography.pillLabelSize, weight: .regular, design: .default)
HaloClosedPill.swift	typography-debt	1	return .system(size: HaloTypography.pillLabelSize, weight: .semibold, design: .default)
HaloClosedPill.swift	typography-debt	1	return .system(size: HaloTypography.pillValueSize, weight: .regular, design: .monospaced)
HaloEmptyState.swift	sf-symbol	1	.font(.system(size: 34, weight: .thin))
HaloEmptyState.swift	typography-debt	1	.font(.system(size: 11, weight: .regular))
HaloEmptyState.swift	typography-debt	1	.font(.system(size: HaloTypography.emptySubtitleSize, weight: .regular))
HaloEmptyState.swift	typography-debt	1	.font(.system(size: HaloTypography.emptyTitleSize, weight: .semibold))
HaloHeaderControls.swift	sf-symbol	1	.font(.system(size: 13, weight: .regular))
HaloInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 11, weight: .regular))
HaloInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 9, weight: .regular))
HaloInstallHooksHint.swift	typography-debt	1	.font(.system(size: HaloTypography.emptySubtitleSize, weight: .regular))
HaloInstallHooksHint.swift	typography-debt	1	.font(.system(size: HaloTypography.keycapSize, weight: .semibold))
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.sectionHeaderSize, weight: .bold))
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.sectionHeaderSize, weight: .bold))
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.sectionHeaderSize, weight: .medium).monospacedDigit())
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.summaryLabelSize))
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.summaryLabelSize).monospacedDigit())
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.summaryLabelSize, weight: .regular))
HaloSessionListScaffold.swift	typography-debt	1	.font(.system(size: HaloTypography.summaryNumberSize, weight: .bold).monospacedDigit())
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .regular))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .regular))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .bold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .regular))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .regular))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 12, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 13, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 13, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 24))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .regular))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
HaloSessionRow.swift	sf-symbol	1	.font(.system(size: 9.5, weight: .bold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: 10, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .regular, design: .monospaced))
HaloSessionRow.swift	typography-debt	1	font: .system(size: 10.5, weight: .regular),
HaloSessionRow.swift	typography-debt	1	iconFont: .system(size: 10.5, weight: .regular),
HaloSessionRow.swift	typography-debt	1	font: .system(size: HaloTypography.diffSize, weight: .regular, design: .monospaced),
HaloSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .medium))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: 13, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.activitySize, weight: .medium))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.activitySize, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.ageSize, weight: .regular).monospacedDigit())
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.branchDisambSize, weight: .regular, design: .monospaced))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.commandSize, weight: .regular, design: .monospaced))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.heroSubtitleSize, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.heroTitleSize, weight: .semibold))
IslandDiffRenderer.swift	typography-debt	1	static let sharedFont: Font = .system(size: 11.5, weight: .regular, design: .monospaced)
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.jumpChipSize, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.jumpChipSize, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.keycapSize, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.metaChipSize, weight: .regular).monospacedDigit())
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.metadataKeySize, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.monogramSize, weight: .bold, design: .default))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.nestHeaderSize, weight: .bold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.nestHeaderSize, weight: .semibold).monospacedDigit())
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.nestHeaderSize, weight: .semibold).monospacedDigit())
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.outcomeBadgeSize, weight: .bold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.subagentElapsedSize, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.subagentElapsedSize, weight: .regular).monospacedDigit())
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.subagentTaskSize, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.subagentTypeSize, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.todoSize, weight: .regular))
HaloSessionRow.swift	typography-debt	1	.font(.system(size: HaloTypography.workspaceTitleSize, weight: .semibold))
HaloSessionRow.swift	typography-debt	1	.system(size: HaloTypography.metadataValueSize, weight: .medium)
HaloSessionRow.swift	typography-debt	1	.system(size: HaloTypography.metadataValueSize, weight: .medium, design: .monospaced).monospacedDigit()
HaloSessionRow.swift	typography-debt	1	baseFont: .system(size: HaloTypography.commandSize, weight: .regular, design: .monospaced)
HaloUsageMeterCard.swift	typography-debt	1	.font(.system(size: HaloTypography.meterLabelSize, weight: .medium))
HaloUsageMeterCard.swift	typography-debt	1	.font(.system(size: HaloTypography.meterValueSize, weight: .semibold))
HaloUsageMeterCard.swift	typography-debt	1	.font(.system(size: HaloTypography.summaryLabelSize, weight: .bold))
HaloUsageMeterCard.swift	typography-debt	1	.font(.system(size: HaloTypography.thresholdPillSize, weight: .bold))
HaloUsageMeterCard.swift	typography-debt	1	.font(.system(size: HaloTypography.usageValueSize, weight: .regular))
HaloUsageSummary.swift	typography-debt	1	.font(.system(size: HaloTypography.usageKickerSize, weight: .semibold))
HaloUsageSummary.swift	typography-debt	1	.font(.system(size: HaloTypography.usageValueSize, weight: .semibold))
InstrumentBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: InstrumentTypography.microLabelSize, weight: .regular, design: .monospaced))
InstrumentClosedPill.swift	overflow-exemption	1	.font(.system(size: max(5, size * 0.55), weight: .bold, design: .monospaced))
InstrumentEmptyState.swift	typography-debt	1	.font(.system(size: InstrumentTypography.microLabelSize, weight: .regular, design: .monospaced))
InstrumentHeaderControls.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
InstrumentInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
InstrumentInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
InstrumentSessionListScaffold.swift	typography-debt	1	.font(.system(size: InstrumentTypography.countSize, weight: .bold, design: .monospaced))
InstrumentSessionListScaffold.swift	typography-debt	1	.font(.system(size: InstrumentTypography.microLabelSize, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .bold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 10.5, weight: .semibold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .bold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .bold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 12, weight: .bold))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 22))
InstrumentSessionRow.swift	sf-symbol	1	.font(.system(size: 9.5, weight: .semibold))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10, weight: .semibold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .bold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .bold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11, weight: .semibold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .bold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .medium, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .semibold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.font(.system(size: 11.5, weight: .semibold, design: .monospaced))
InstrumentSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .monospaced)
InstrumentSessionRow.swift	typography-debt	1	.system(size: size * typeScale, weight: weight, design: .monospaced)
InstrumentUsageSummary.swift	typography-debt	1	.font(.system(size: InstrumentTypography.countSize, weight: .bold, design: .monospaced))
IslandBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: 12))
IslandBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: 14, weight: .medium))
IslandEmptyState.swift	typography-debt	1	.font(.system(size: 12))
IslandEmptyState.swift	typography-debt	1	.font(.system(size: 14, weight: .medium))
IslandHeaderControls.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
IslandInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
IslandInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 12, weight: .semibold))
IslandInstallHooksHint.swift	typography-debt	1	.font(.system(size: 12, weight: .medium))
IslandNotificationCard.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium))
IslandSessionListScaffold.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium, design: .monospaced))
IslandSessionListScaffold.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced))
IslandSessionListScaffold.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced))
IslandSessionListScaffold.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced))
IslandUsageSummary.swift	typography-debt	1	.font(.system(size: 10, weight: .semibold))
IslandUsageSummary.swift	typography-debt	1	.font(.system(size: 10.5, weight: .semibold, design: .monospaced))
IslandUsageSummary.swift	typography-debt	1	.font(.system(size: 11, weight: .semibold))
IslandUsageSummary.swift	typography-debt	1	.font(.system(size: 11.5, weight: .bold, design: .monospaced))
PouredBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: 12))
PouredBootstrapPlaceholder.swift	typography-debt	1	.font(.system(size: 14, weight: .medium))
PouredClosedPill.swift	overflow-exemption	1	.font(.system(size: max(5, size * 0.55), weight: .bold, design: .monospaced))
PouredClosedPill.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
PouredClosedPill.swift	sf-symbol	1	.font(.system(size: 12, weight: .bold))
PouredClosedPill.swift	sf-symbol	1	.font(.system(size: 12, weight: .bold))
PouredClosedPill.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
PouredClosedPill.swift	typography-debt	1	.font(.system(size: 11, weight: .semibold, design: .monospaced))
PouredEmptyState.swift	sf-symbol	1	.font(.system(size: 9, weight: .bold))
PouredEmptyState.swift	typography-debt	1	.font(.system(size: 11, weight: .regular))
PouredHeaderControls.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
PouredInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
PouredInstallHooksHint.swift	sf-symbol	1	.font(.system(size: 12, weight: .semibold))
PouredSessionListScaffold.swift	typography-debt	1	.font(.system(size: 10.5, weight: .medium).monospacedDigit())
PouredSessionListScaffold.swift	typography-debt	1	.font(.system(size: 11))
PouredSessionListScaffold.swift	typography-debt	1	.font(.system(size: 11).monospacedDigit())
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .bold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 10, weight: .semibold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .bold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 11, weight: .semibold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 12, weight: .semibold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 12, weight: .semibold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 13, weight: .semibold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 24))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .bold))
PouredSessionRow.swift	sf-symbol	1	.font(.system(size: 9, weight: .semibold))
PouredSessionRow.swift	typography-debt	1	.font(.system(size: 12, weight: .regular))
PouredUsageMeterCard.swift	typography-debt	1	.font(.system(size: 10, weight: .semibold))
PouredUsageMeterCard.swift	typography-debt	1	.font(.system(size: 11, weight: .semibold))
PouredUsageMeterCard.swift	typography-debt	1	.font(.system(size: 12, weight: .medium))
PouredUsageMeterCard.swift	typography-debt	1	.font(.system(size: 9, weight: .bold))
PouredUsageSummary.swift	typography-debt	1	.font(.system(size: 10, weight: .medium))
"""#
}
